name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test execution
      working-directory: ${{github.workspace}}/build
      run: |
        ./hello_app
        if [ $? -ne 0 ]; then
          echo "Application exited with non-zero status code"
          exit 1
        fi
