name: Dogfood Branch Deletion

on:
  pull_request:
    types: [unlabeled]

jobs:
  delete_dogfood_branch:
    if: |
      github.event.label.name == 'dogfood'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete dogfood branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          dogfood_branch="dogfood/${{ github.event.pull_request.head.ref }}"
          echo "Attempting to delete branch: $dogfood_branch"
          git push origin :"$dogfood_branch" || true
