name: PR Green Checker

on:
  workflow_run:
    workflows: ["C++ CI"]
    types: [completed]

jobs:
  check_pr_status:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Check suite conclusion: ${{ github.event.check_suite.conclusion }}"
          echo "Head SHA: ${{ github.event.check_suite.head_sha }}"
