name: PR Green Checker

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches-ignore:
      - main
      - 'dogfood/**'

jobs:
  dogfood_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR and create dogfood branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/dogfood-branch-create.ts')
            await script({github, context})
