name: PR Green Checker

on:
  workflow_run:
    workflows: ["C++ CI"]
    types:
      - completed

jobs:
  check_pr_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check workflow conclusion
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head SHA: ${{ github.event.workflow_run.head_sha }}"
          
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "C++ CI workflow passed successfully!"
          else
            echo "C++ CI workflow failed or was cancelled."
            exit 1
          fi
