name: Create dogfood branch

on:
  pull_request:
    types: [labeled]
  check_suite:
    types: [completed]

jobs:
  dogfood_check:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR info from check_suite
        if: github.event_name == 'status'
        id: pr_from_check_suite
        uses: actions/github-script@v7
        with:
          script: |
            const commitSha = context.payload.commit.sha;
            console.log(`Looking for PRs with commit: ${commitSha}`);
            
            // Find PRs associated with this commit
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha
            });
            
            if (prs && prs.length > 0) {
              console.log(`Found PR #${prs[0].number}`);
              core.setOutput('pr_number', prs[0].number);
            } else {
              console.log('No PRs found for this commit');
            }
      - name: Determine PR number
        id: determine_pr
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "check_suite" ]]; then
            echo "pr_number=${{ steps.pr_from_check_suite.outputs.pr_number }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=" >> $GITHUB_OUTPUT
          fi
      - name: Fetch PR details
        id: pr_details
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.determine_pr.outputs.pr_number }}
        with:
          script: |
            const pr_number = process.env.PR_NUMBER
            if (!pr_number) {
              core.setOutput('skip', 'true');
              return;
            }
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number
            });
            core.setOutput('pr_head', pr.head.sha);
            core.setOutput('pr_number', pr_number);
            if (pr.labels.find(l => l.name === 'dogfood')) {
              core.setOutput('has_dogfood', 'true');
            } else {
              core.setOutput('has_dogfood', 'false');
            }
      - name: Check if all checks are green
        id: checks_green
        if: steps.pr_details.outputs.has_dogfood == 'true'
        uses: actions/github-script@v7
        env:
          PR_HEAD: ${{ steps.pr_details.outputs.pr_head }}
        with:
          script: |
            const status = await github.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: process.env.PR_HEAD
            });
            if (status.state === 'success') {
              core.setOutput('green', 'true');
            } else {
              core.setOutput('green', 'false');
            }
      - name: Checkout repository
        if: steps.pr_details.outputs.has_dogfood == 'true' && steps.checks_green.outputs.green == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Create dogfood branch
        if: steps.pr_details.outputs.has_dogfood == 'true' && steps.checks_green.outputs.green == 'true'
        run: |
          echo git config user.name "github-actions[bot]"
          echo git config user.email "github-actions[bot]@users.noreply.github.com"
          echo git checkout -b dogfood/${{ github.event.pull_request.head.ref }}
          echo git push -f origin dogfood/${{ github.event.pull_request.head.ref }}
