name: Dogfood Branch Creation

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches-ignore:
      - main
      - 'dogfood/**'
  pull_request:
    types: [labeled]

jobs:
  dogfood_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract PR information
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/workflows/get-pr-information.js')
            await script({github, context, core})
